#Default profile
spring:
  profiles: default
  
# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 1111   # HTTP (Tomcat) portance.hosname=localhost
  
# Security
security:
 user:
    name: admin
    password: admin