spring:
  application:
    name: eurekaServiceDiscoveryA # ==> This is Service-Id
     
 
---
# Items that apply to ALL profiles:   
eureka:
  instance:
    appname: eurekaServiceDiscoveryA  # ==> This is a instance of eurekaServiceDiscoveryA
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
server:
  port: 8000