spring:
  application:
    name: zuulAPIGateway # ==> This is Service-Id
     
server:
  port: 8002
  
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka